baseURL = 'https://menulis.xyz/'
languageCode = 'id'
title = 'Menulis!'
theme = 'menulis-theme'

[params]
  author = 'hilmanski'
  description = 'Tulisan tentang menulis'

[permalinks]
  posts = '/:slug/'